swagger: "2.0"
info:
  description: "Experimental AWS serverless architecture for post-processing 3D models from Autodesk Forge to additional formats such as glTF, glb, or Usdz."
  version: "1.0.0"
  title: "Forge Extra Derivatives"
host: "m5ey85w3lk.execute-api.us-west-2.amazonaws.com"
basePath: "/Prod"
schemes:
- "https"
paths:
  /jobs/{urn}/{guid}:
    get:
      tags:
      - "job"
      summary: "Get conversion status"
      description: "Returns the status of a conversion job for a specific model."
      operationId: "getJobStatus"
      security:
        - ForgeAuth2L: ["viewables:read"]
        - ForgeAuth3L: ["viewables:read"]
      produces:
      - "application/json"
      parameters:
      - name: "urn"
        in: "path"
        description: "Forge model URN"
        required: true
        type: "string"
      - name: "guid"
        in: "path"
        description: "Forge model viewable GUID"
        required: true
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Job"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
        404:
          description: "Not Found"
        500:
          description: "Internal Server Error"
    post:
      tags:
      - "job"
      summary: "Start conversion"
      description: "Starts the conversion job for a specific model."
      operationId: "startJob"
      security:
        - ForgeAuth2L: ["viewables:read"]
        - ForgeAuth3L: ["viewables:read"]
      produces:
      - "application/json"
      parameters:
      - name: "urn"
        in: "path"
        description: "Forge model URN"
        required: true
        type: "string"
      - name: "guid"
        in: "path"
        description: "Forge model viewable GUID"
        required: true
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Job"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
        404:
          description: "Not Found"
        500:
          description: "Internal Server Error"
  /jobs/{urn}/{guid}/signedurl:
    post:
      tags:
      - "job"
      summary: "Generate download URLs"
      description: "Generates public URLs to download conversion artifacts."
      operationId: "generateUrls"
      security:
        - ForgeAuth2L: ["viewables:read"]
        - ForgeAuth3L: ["viewables:read"]
      produces:
      - "application/json"
      parameters:
      - name: "urn"
        in: "path"
        description: "Forge model URN"
        required: true
        type: "string"
      - name: "guid"
        in: "path"
        description: "Forge model viewable GUID"
        required: true
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Artifacts"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
        404:
          description: "Not Found"
        500:
          description: "Internal Server Error"
definitions:
  Job:
    type: "object"
    properties:
      urn:
        type: "string"
        description: "Forge model URN."
      guid:
        type: "string"
        description: "Forge model viewable GUID."
      step:
        type: "string"
        description: "Short description of the current conversion step."
      status:
        type: "string"
        description: "Conversion job status."
        enum:
        - "inprogress"
        - "failed"
        - "success"
    required:
      - urn
      - guid
      - status
  Artifacts:
    type: "object"
    properties:
      Svf:
        type: "string"
        description: "Temporary presigned URL for downloading the conversion output."
      Gltf:
        type: "string"
        description: "Temporary presigned URL for downloading the conversion output."
      Glb:
        type: "string"
        description: "Temporary presigned URL for downloading the conversion output."
      GlbDraco:
        type: "string"
        description: "Temporary presigned URL for downloading the conversion output."
      Usdz:
        type: "string"
        description: "Temporary presigned URL for downloading the conversion output."
securityDefinitions:
  ForgeAuth2L:
    type: oauth2
    flow: application
    description: Autodesk Forge 2-legged authentication.
    tokenUrl: https://developer.api.autodesk.com/authentication/v1/authenticate
    scopes:
      "viewables:read": Grants read access to Model Derivative service viewables.
  ForgeAuth3L:
    type: oauth2
    flow: accessCode
    description: Autodesk Forge 3-legged authentication.
    authorizationUrl: https://developer.api.autodesk.com/authentication/v1/authorize
    tokenUrl: https://developer.api.autodesk.com/authentication/v1/gettoken
    scopes:
      "viewables:read": Grants read access to Model Derivative service viewables.